export enum Collections {
  auth = 'auth',
  user = 'user',
  token = 'token',
  listing = 'listing',
  newsletter_subscription = 'newsletter_subscription',
  category = 'category',
  subcategory = 'subcategory',
  article = 'article',
  property_request = 'property_request',
  verification = 'verification',
  report = 'report',
  conversation = 'conversation',
  message = 'message',
  cart = 'cart',
  notification = 'notification',
  subscription = 'subscription',
  transaction = 'transaction',
}
